services:
  scrutiny:
    container_name: scrutiny
    image: ghcr.io/analogj/scrutiny:master-omnibus
    restart: unless-stopped
    ports:
      - "8080:8080" # Web Interface
      - "8086:8086" # InfluxDB API
    volumes:
      - /run/udev:/run/udev:ro
      - ./config:/opt/scrutiny/config
      - ./influxdb:/opt/scrutiny/influxdb
    environment:
      - SCRUTINY_WEB_INFLUXDB_HOST=localhost
    
    cap_add:
      - SYS_RAWIO # Allows S.M.A.R.T. monitoring
      - SYS_ADMIN # Allows disk querying
    
    devices:
      - "/dev/sda:/dev/sda" # System SSD
      - "/dev/sdb:/dev/sdb" # RAID Array Disk 1
      - "/dev/sdc:/dev/sdc" # RAID Array Disk 2
      - "/dev/sdd:/dev/sdd" # RAID Array Disk 3
      - "/dev/sde:/dev/sde" # Storage Disk 1
      - "/dev/sdf:/dev/sdf" # Storage Disk 2
